// Generated by tools/fonttest/gen_fonts.py. Do not edit.
#pragma once

#include "EpdFontData.h"

#include "fonts/notoserif_7.h"
#include "fonts/notoserif_8.h"
#include "fonts/notoserif_9.h"
#include "fonts/notoserif_10.h"
#include "fonts/notoserif_11.h"
#include "fonts/notoserif_12.h"
#include "fonts/notoserif_14.h"
#include "fonts/literata_7.h"
#include "fonts/literata_8.h"
#include "fonts/literata_9.h"
#include "fonts/literata_10.h"
#include "fonts/literata_11.h"
#include "fonts/literata_12.h"
#include "fonts/literata_14.h"
#include "fonts/sourceserif4_7.h"
#include "fonts/sourceserif4_8.h"
#include "fonts/sourceserif4_9.h"
#include "fonts/sourceserif4_10.h"
#include "fonts/sourceserif4_11.h"
#include "fonts/sourceserif4_12.h"
#include "fonts/sourceserif4_14.h"
#include "fonts/merriweather_7.h"
#include "fonts/merriweather_8.h"
#include "fonts/merriweather_9.h"
#include "fonts/merriweather_10.h"
#include "fonts/merriweather_11.h"
#include "fonts/merriweather_12.h"
#include "fonts/merriweather_14.h"
#include "fonts/bitter_7.h"
#include "fonts/bitter_8.h"
#include "fonts/bitter_9.h"
#include "fonts/bitter_10.h"
#include "fonts/bitter_11.h"
#include "fonts/bitter_12.h"
#include "fonts/bitter_14.h"
#include "fonts/charis_7.h"
#include "fonts/charis_8.h"
#include "fonts/charis_9.h"
#include "fonts/charis_10.h"
#include "fonts/charis_11.h"
#include "fonts/charis_12.h"
#include "fonts/charis_14.h"
#include "fonts/lora_7.h"
#include "fonts/lora_8.h"
#include "fonts/lora_9.h"
#include "fonts/lora_10.h"
#include "fonts/lora_11.h"
#include "fonts/lora_12.h"
#include "fonts/lora_14.h"
#include "fonts/atkinson_7.h"
#include "fonts/atkinson_8.h"
#include "fonts/atkinson_9.h"
#include "fonts/atkinson_10.h"
#include "fonts/atkinson_11.h"
#include "fonts/atkinson_12.h"
#include "fonts/atkinson_14.h"

constexpr int FONT_SIZE_COUNT = 7;
constexpr int FONT_SIZES_PT[FONT_SIZE_COUNT] = {7, 8, 9, 10, 11, 12, 14};

struct TestFont {
  const char* name;
  const EpdFontData* sizes[FONT_SIZE_COUNT];
};

constexpr TestFont TEST_FONTS[] = {
    {"Noto Serif", {&notoserif_7, &notoserif_8, &notoserif_9, &notoserif_10, &notoserif_11, &notoserif_12, &notoserif_14}},
    {"Literata", {&literata_7, &literata_8, &literata_9, &literata_10, &literata_11, &literata_12, &literata_14}},
    {"Source Serif 4", {&sourceserif4_7, &sourceserif4_8, &sourceserif4_9, &sourceserif4_10, &sourceserif4_11, &sourceserif4_12, &sourceserif4_14}},
    {"Merriweather", {&merriweather_7, &merriweather_8, &merriweather_9, &merriweather_10, &merriweather_11, &merriweather_12, &merriweather_14}},
    {"Bitter", {&bitter_7, &bitter_8, &bitter_9, &bitter_10, &bitter_11, &bitter_12, &bitter_14}},
    {"Charis SIL", {&charis_7, &charis_8, &charis_9, &charis_10, &charis_11, &charis_12, &charis_14}},
    {"Lora", {&lora_7, &lora_8, &lora_9, &lora_10, &lora_11, &lora_12, &lora_14}},
    {"Atkinson Hyperlegible", {&atkinson_7, &atkinson_8, &atkinson_9, &atkinson_10, &atkinson_11, &atkinson_12, &atkinson_14}},
};
constexpr int TEST_FONT_COUNT = sizeof(TEST_FONTS) / sizeof(TEST_FONTS[0]);
