#!/usr/bin/env python3
"""Generates the font-comparison firmware's fonts (src/fonttest/).

Put the source .ttf files in tools/fonttest/ttf/ (gitignored), then:

  pip install freetype-py fonttools brotli
  python tools/fonttest/gen_fonts.py

Every font is pinned to Regular (wght 400). Variable fonts with an optical
size axis get the instance for each point size, as their designers intend.
Glyphs are trimmed to basic Latin + typographic punctuation to keep flash
small, and converted with the reader's own settings (--pnum,
--mono-threshold 4) so the comparison matches what a book page would show.
"""

import os
import re
import subprocess
import sys
import tempfile

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TTF_DIR = os.path.join(ROOT, "tools", "fonttest", "ttf")
OUT_DIR = os.path.join(ROOT, "src", "fonttest", "fonts")
CATALOG = os.path.join(ROOT, "src", "fonttest", "FontCatalog.h")
FONTCONVERT = os.path.join(ROOT, "tools", "fontconvert.py")

SIZES = [7, 8, 9, 10, 11, 12, 14]

# (display name, symbol prefix, candidate file names). The first file found
# wins; fonts with no file present are skipped (Bookerly and ChareInk are not
# freely downloadable).
FONTS = [
    ("Bookerly", "bookerly", ["Bookerly-Regular.ttf", "Bookerly.ttf"]),
    ("Noto Serif", "notoserif", ["NotoSerif-Regular.ttf"]),
    ("Literata", "literata", ["Literata[opsz,wght].ttf", "Literata-Regular.ttf"]),
    ("Source Serif 4", "sourceserif4", ["SourceSerif4[opsz,wght].ttf", "SourceSerif4-Regular.ttf"]),
    ("Merriweather", "merriweather", ["Merriweather[opsz,wdth,wght].ttf", "Merriweather-Regular.ttf"]),
    ("Bitter", "bitter", ["Bitter[wght].ttf", "Bitter-Regular.ttf"]),
    ("Charis SIL", "charis", ["CharisSIL-Regular.ttf"]),
    ("ChareInk", "chareink", ["ChareInk-Regular.ttf", "ChareInk.ttf"]),
    ("Lora", "lora", ["Lora[wght].ttf", "Lora-Regular.ttf"]),
    ("Atkinson Hyperlegible", "atkinson", ["AtkinsonHyperlegible-Regular.ttf"]),
]

# Basic Latin, Latin-1 punctuation, curly quotes, dashes, ellipsis.
UNICODES = list(range(0x20, 0x7F)) + [0xA0, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026]


def static_instance(path, size):
    font = TTFont(path)
    if "fvar" in font:
        pins = {}
        for axis in font["fvar"].axes:
            if axis.axisTag == "wght":
                pins["wght"] = 400
            elif axis.axisTag == "opsz":
                pins["opsz"] = max(axis.minValue, min(axis.maxValue, size))
            else:
                pins[axis.axisTag] = axis.defaultValue
        font = instancer.instantiateVariableFont(font, pins)
    opts = subset.Options()
    opts.layout_features = ["*"]  # keep kern and pnum
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    return font


def convert(name, size, ttf_path):
    result = subprocess.run(
        [sys.executable, FONTCONVERT, name, str(size), ttf_path, "--pnum", "--mono-threshold", "4"],
        check=True,
        capture_output=True,
        text=True,
    )
    # Absolute temp paths in the "Command used" line would change every run.
    return re.sub(r"Command used: .*", f"Command used: tools/fonttest/gen_fonts.py ({name})", result.stdout)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for f in os.listdir(OUT_DIR):
        if f.endswith(".h"):
            os.remove(os.path.join(OUT_DIR, f))

    found = []
    for display, prefix, candidates in FONTS:
        path = next((os.path.join(TTF_DIR, c) for c in candidates if os.path.exists(os.path.join(TTF_DIR, c))), None)
        if not path:
            print(f"skip {display}: none of {candidates} in {TTF_DIR}")
            continue
        with tempfile.TemporaryDirectory() as tmp:
            for size in SIZES:
                inst = os.path.join(tmp, f"{prefix}{size}.ttf")
                static_instance(path, size).save(inst)
                header = convert(f"{prefix}_{size}", size, inst)
                with open(os.path.join(OUT_DIR, f"{prefix}_{size}.h"), "w") as out:
                    out.write(header)
        print(f"{display}: {os.path.basename(path)}")
        found.append((display, prefix))

    with open(CATALOG, "w") as out:
        out.write("// Generated by tools/fonttest/gen_fonts.py. Do not edit.\n#pragma once\n\n")
        out.write('#include "EpdFontData.h"\n\n')
        for _, prefix in found:
            for size in SIZES:
                out.write(f'#include "fonts/{prefix}_{size}.h"\n')
        out.write(f"\nconstexpr int FONT_SIZE_COUNT = {len(SIZES)};\n")
        out.write(f"constexpr int FONT_SIZES_PT[FONT_SIZE_COUNT] = {{{', '.join(map(str, SIZES))}}};\n\n")
        out.write("struct TestFont {\n  const char* name;\n  const EpdFontData* sizes[FONT_SIZE_COUNT];\n};\n\n")
        out.write("constexpr TestFont TEST_FONTS[] = {\n")
        for display, prefix in found:
            refs = ", ".join(f"&{prefix}_{s}" for s in SIZES)
            out.write(f'    {{"{display}", {{{refs}}}}},\n')
        out.write("};\nconstexpr int TEST_FONT_COUNT = sizeof(TEST_FONTS) / sizeof(TEST_FONTS[0]);\n")
    print(f"{len(found)} fonts x {len(SIZES)} sizes -> {CATALOG}")


if __name__ == "__main__":
    main()
