#pragma once

// Proportional 1-bit font rendering for fonts generated by
// lib/EpdFont/scripts/fontconvert.py (uncompressed, 1-bit). Pure C++ so the
// host preview/test tools share it with the firmware.

#include <cstddef>
#include <cstdint>

#include "EpdFontData.h"

namespace font {

// Decodes one UTF-8 codepoint and advances p (bounded by end). Invalid bytes
// yield U+FFFD and consume one byte.
uint32_t nextCodepoint(const char*& p, const char* end);

const EpdGlyph* glyph(const EpdFontData* f, uint32_t cp);

// Width in pixels of s[0..len), including kerning between its glyphs.
int textWidth(const EpdFontData* f, const char* s, size_t len);

// 1bpp framebuffer, MSB-first, bit 1 = white (matches the vendor Paint buffer).
struct Canvas {
  uint8_t* buf;
  int width;
  int height;
};

// Draws s[0..len) with its baseline at y; returns the advance in pixels.
int drawText(const Canvas& c, const EpdFontData* f, int x, int baselineY, const char* s, size_t len,
             bool black = true);

}  // namespace font
